name: SLIDE SLAM Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    name: "SLIDE_SLAM build-and-test"
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pull Prebuilt Docker Image
      run: |
        docker pull xurobotics/slide-slam:latest

    - name: Set Up Workspace and Clone Repo
      run: |
        mkdir -p ~/slideslam_docker_ws/src
        cd ~/slideslam_docker_ws/src
        git clone https://github.com/lunarlab-gatech/SLIDE_SLAM.git

    - name: Build Docker Image
      run: |
        cd ~/slideslam_docker_ws/src/SLIDE_SLAM/docker
        git checkout apriltag
        ./build_image.sh

    - name: Run Docker Container
      run: |
        cd ~/slideslam_docker_ws/src/SLIDE_SLAM/docker
        export WS_PATH="$(pwd)"
        chmod +x run_container.sh
        ./run_container.sh --no-gpu

    - name: Build SLIDE_SLAM inside Container
      run: |
        docker exec slideslam_ros sh -c "catkin_make && source devel/setup.bash"        docker exec slideslam_ros sh -c "source devel/setup.bash"

    - name: Run SLIDE_SLAM Tests
      run: |
        docker exec -it slideslam_ros sh -c "catkin_make run_tests"